# Multi-Class Classification: Naive Bayes Classification with Sklearn

According to Bayes Theorem, the various features are mutually independent. For two independent events, P(A,B) = P(A)P(B). This assumption of Bayes Theorem is probably never encountered in practice, hence it accounts for the “naive” part in Naive Bayes. Bayes’ Theorem is stated as: P(a|b) = (P(b|a) * P(a)) / P(b). Where P(a|b) is the probability of a given b.

To implement the Naive Bayes Classification, we shall use a very famous Iris Flower Dataset that consists of 3 classes of flowers. In this, there are 4 independent variables namely the, sepal_length, sepal_width, petal_length and petal_width. The dependent variable is the species which we will predict using the four independent features of the flowers. There are 3 classes of species namely setosa, versicolor and the virginica. This dataset was originally introduced in 1936 by Ronald Fisher. Using the various features of the flower (independent variables), we have to classify a given flower using Naive Bayes Classification model.

# Import libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score 

## Load data

In [2]:
# load data and store in df
url = 'https://raw.githubusercontent.com/mk-gurucharan/Classification/master/IrisDataset.csv'
df = pd.read_csv(url)
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

## Explore data

In [3]:
# show descriptive statistics
df.describe(include="all")

sepal_length  sepal_width  petal_length  petal_width    species
count     150.000000   150.000000    150.000000   150.000000        150
unique           NaN          NaN           NaN          NaN          3
top              NaN          NaN           NaN          NaN  virginica
freq             NaN          NaN           NaN          NaN         50
mean        5.843333     3.054000      3.758667     1.198667        NaN
std         0.828066     0.433594      1.764420     0.763161        NaN
min         4.300000     2.000000      1.000000     0.100000        NaN
25%         5.100000     2.800000      1.600000     0.300000        NaN
50%         5.800000     3.000000      4.350000     1.300000        NaN
75%         6.400000     3.300000      5.100000     1.800000        NaN
max         7.900000     4.400000      6.900000     2.500000        NaN

## Declare features and targets

In [4]:
# create feature (X) and target (y) variables
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

## Scale features

In [5]:
# create and fit scaler
scaler = StandardScaler()
scaler.fit(X)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [6]:
# standardize features
X_scaled = scaler.transform(X)

## Train-Test Split

In [7]:
# 80:20 split
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size = 0.2, random_state = 1)

## Train model

In this step, we introduce the class GaussianNB that is used from the sklearn.naive_bayes library. Here, we have used a Gaussian model, there are several other models such as Bernoulli, Categorical and Multinomial. Here, we assign the GaussianNB class to the variable classifier and fit the X_train and y_train values to it for training purpose.

In [8]:
# build and train model
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

## Test model

In [9]:
# make predictions and test model 
yhat = classifier.predict(X_test)
yhat

array(['setosa', 'versicolor', 'versicolor', 'setosa', 'virginica',
       'versicolor', 'virginica', 'setosa', 'setosa', 'virginica',
       'versicolor', 'setosa', 'virginica', 'versicolor', 'versicolor',
       'setosa', 'versicolor', 'versicolor', 'setosa', 'setosa',
       'versicolor', 'versicolor', 'virginica', 'setosa', 'virginica',
       'versicolor', 'setosa', 'setosa', 'versicolor', 'virginica'],
      dtype='<U10')

In [10]:
# confusion matrix
cm = confusion_matrix(y_test, yhat)
print ("Accuracy : ", accuracy_score(y_test, yhat))
print(cm)

Accuracy :  0.9666666666666667
[[11  0  0]
 [ 0 12  1]
 [ 0  0  6]]


In [11]:
# show actuals and predictions in a df
eval_df = pd.DataFrame({'Real Values':y_test, 'Predicted Values':yhat})
eval_df

Real Values Predicted Values
0       setosa           setosa
1   versicolor       versicolor
2   versicolor       versicolor
3       setosa           setosa
4    virginica        virginica
5   versicolor       versicolor
6    virginica        virginica
7       setosa           setosa
8       setosa           setosa
9    virginica        virginica
10  versicolor       versicolor
11      setosa           setosa
12   virginica        virginica
13  versicolor       versicolor
14  versicolor       versicolor
15      setosa           setosa
16  versicolor       versicolor
17  versicolor       versicolor
18      setosa           setosa
19      setosa           setosa
20  versicolor       versicolor
21  versicolor       versicolor
22  versicolor        virginica
23      setosa           setosa
24   virginica        virginica
25  versicolor       versicolor
26      setosa           setosa
27      setosa           setosa
28  versicolor       versicolor
29   virginica        virginica